# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './Task4.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(800, 600)
        self.inputMatrix = QtWidgets.QTableWidget(Frame)
        self.inputMatrix.setGeometry(QtCore.QRect(10, 10, 381, 251))
        self.inputMatrix.setObjectName("inputMatrix")
        self.inputMatrix.setColumnCount(0)
        self.inputMatrix.setRowCount(0)
        self.outputMatrix = QtWidgets.QTableWidget(Frame)
        self.outputMatrix.setGeometry(QtCore.QRect(410, 10, 381, 251))
        self.outputMatrix.setObjectName("outputMatrix")
        self.outputMatrix.setColumnCount(0)
        self.outputMatrix.setRowCount(0)
        self.formattButton = QtWidgets.QPushButton(Frame)
        self.formattButton.setGeometry(QtCore.QRect(310, 320, 181, 61))
        self.formattButton.setObjectName("formattButton")

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.formattButton.setText(_translate("Frame", "Format Matrix"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Frame = QtWidgets.QFrame()
    ui = Ui_Frame()
    ui.setupUi(Frame)
    Frame.show()
    sys.exit(app.exec_())
