# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './Task1.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(800, 600)
        self.dataTable = QtWidgets.QTableWidget(Frame)
        self.dataTable.setGeometry(QtCore.QRect(10, 50, 451, 441))
        self.dataTable.setObjectName("dataTable")
        self.dataTable.setColumnCount(0)
        self.dataTable.setRowCount(0)
        self.addKeeperButton = QtWidgets.QPushButton(Frame)
        self.addKeeperButton.setGeometry(QtCore.QRect(550, 100, 161, 51))
        self.addKeeperButton.setObjectName("addKeeperButton")
        self.sortButton = QtWidgets.QPushButton(Frame)
        self.sortButton.setGeometry(QtCore.QRect(500, 180, 251, 51))
        self.sortButton.setObjectName("sortButton")

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.addKeeperButton.setText(_translate("Frame", "Add Random Keeper"))
        self.sortButton.setText(_translate("Frame", "Keepers that work more than 10 years"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Frame = QtWidgets.QFrame()
    ui = Ui_Frame()
    ui.setupUi(Frame)
    Frame.show()
    sys.exit(app.exec_())
