# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './Task5.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(800, 600)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Frame)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 801, 221))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.markinput = QtWidgets.QLineEdit(Frame)
        self.markinput.setGeometry(QtCore.QRect(20, 280, 113, 22))
        self.markinput.setObjectName("markinput")
        self.modelInput = QtWidgets.QLineEdit(Frame)
        self.modelInput.setGeometry(QtCore.QRect(20, 310, 113, 22))
        self.modelInput.setObjectName("modelInput")
        self.maxSpeedInput = QtWidgets.QLineEdit(Frame)
        self.maxSpeedInput.setGeometry(QtCore.QRect(20, 340, 113, 22))
        self.maxSpeedInput.setObjectName("maxSpeedInput")
        self.maxHeightInput = QtWidgets.QLineEdit(Frame)
        self.maxHeightInput.setGeometry(QtCore.QRect(20, 370, 113, 22))
        self.maxHeightInput.setObjectName("maxHeightInput")
        self.typeComboBox = QtWidgets.QComboBox(Frame)
        self.typeComboBox.setGeometry(QtCore.QRect(20, 400, 111, 22))
        self.typeComboBox.setObjectName("typeComboBox")
        self.typeComboBox.addItem("Bomber")
        self.typeComboBox.addItem("Airplane")
        self.typeComboBox.addItem("Fighter")
        self.pushButton = QtWidgets.QPushButton(Frame)
        self.pushButton.setGeometry(QtCore.QRect(140, 400, 111, 22))
        self.pushButton.setObjectName("pushButton")
        self.label_4 = QtWidgets.QLabel(Frame)
        self.label_4.setGeometry(QtCore.QRect(140, 280, 101, 21))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Frame)
        self.label_5.setGeometry(QtCore.QRect(140, 310, 101, 21))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Frame)
        self.label_6.setGeometry(QtCore.QRect(140, 340, 151, 21))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Frame)
        self.label_7.setGeometry(QtCore.QRect(140, 370, 151, 21))
        self.label_7.setObjectName("label_7")

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.label_3.setText(_translate("Frame", "TextLabel"))
        self.label_2.setText(_translate("Frame", "TextLabel"))
        self.label.setText(_translate("Frame", "TextLabel"))
        self.pushButton.setText(_translate("Frame", "Add object"))
        self.label_4.setText(_translate("Frame", "Марка"))
        self.label_5.setText(_translate("Frame", "Модель"))
        self.label_6.setText(_translate("Frame", "Максимальна швидкість"))
        self.label_7.setText(_translate("Frame", "Максимальна висота"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Frame = QtWidgets.QFrame()
    ui = Ui_Frame()
    ui.setupUi(Frame)
    Frame.show()
    sys.exit(app.exec_())
