# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './Task3.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(800, 600)
        self.label = QtWidgets.QLabel(Frame)
        self.label.setGeometry(QtCore.QRect(320, 70, 151, 31))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(Frame)
        self.lineEdit.setGeometry(QtCore.QRect(320, 120, 151, 22))
        self.lineEdit.setObjectName("lineEdit")
        self.yearLabel = QtWidgets.QLabel(Frame)
        self.yearLabel.setGeometry(QtCore.QRect(330, 170, 141, 16))
        self.yearLabel.setObjectName("yearLabel")
        self.dateLabel = QtWidgets.QLabel(Frame)
        self.dateLabel.setGeometry(QtCore.QRect(320, 220, 121, 16))
        self.dateLabel.setObjectName("dateLabel")
        self.calculateButton = QtWidgets.QPushButton(Frame)
        self.calculateButton.setGeometry(QtCore.QRect(350, 280, 93, 28))
        self.calculateButton.setObjectName("calculateButton")

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.label.setText(_translate("Frame", "Введіь рік випуску товару"))
        self.yearLabel.setText(_translate("Frame", "(Скільки років товару)"))
        self.dateLabel.setText(_translate("Frame", "Дата в об\'єкті:"))
        self.calculateButton.setText(_translate("Frame", "Розрахувати"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Frame = QtWidgets.QFrame()
    ui = Ui_Frame()
    ui.setupUi(Frame)
    Frame.show()
    sys.exit(app.exec_())
