# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './Task7.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(800, 600)
        self.OS_Result = QtWidgets.QLabel(Frame)
        self.OS_Result.setGeometry(QtCore.QRect(70, 20, 221, 221))
        self.OS_Result.setStyleSheet("background-color:rgb(180,180,180)")
        self.OS_Result.setText("")
        self.OS_Result.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.OS_Result.setObjectName("OS_Result")
        self.Mobile_Result = QtWidgets.QLabel(Frame)
        self.Mobile_Result.setGeometry(QtCore.QRect(500, 20, 221, 221))
        self.Mobile_Result.setStyleSheet("background-color:rgb(180,180,180)")
        self.Mobile_Result.setText("")
        self.Mobile_Result.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.Mobile_Result.setObjectName("Mobile_Result")
        self.verticalLayoutWidget = QtWidgets.QWidget(Frame)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(80, 290, 201, 261))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.OSInstallButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.OSInstallButton.setObjectName("OSInstallButton")
        self.verticalLayout.addWidget(self.OSInstallButton)
        self.OSUpdateButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.OSUpdateButton.setObjectName("OSUpdateButton")
        self.verticalLayout.addWidget(self.OSUpdateButton)
        self.OSWriteCodeButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.OSWriteCodeButton.setObjectName("OSWriteCodeButton")
        self.verticalLayout.addWidget(self.OSWriteCodeButton)
        self.OSTestCodeButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.OSTestCodeButton.setObjectName("OSTestCodeButton")
        self.verticalLayout.addWidget(self.OSTestCodeButton)
        self.OSRebootSystemButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.OSRebootSystemButton.setObjectName("OSRebootSystemButton")
        self.verticalLayout.addWidget(self.OSRebootSystemButton)
        self.OSAddUserButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.OSAddUserButton.setObjectName("OSAddUserButton")
        self.verticalLayout.addWidget(self.OSAddUserButton)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Frame)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(510, 290, 201, 261))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.MobileInstallButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.MobileInstallButton.setObjectName("MobileInstallButton")
        self.verticalLayout_2.addWidget(self.MobileInstallButton)
        self.MobileUpdateButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.MobileUpdateButton.setObjectName("MobileUpdateButton")
        self.verticalLayout_2.addWidget(self.MobileUpdateButton)
        self.pushButton_9 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton_9.setObjectName("pushButton_9")
        self.verticalLayout_2.addWidget(self.pushButton_9)
        self.MobileTestCodeButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.MobileTestCodeButton.setObjectName("MobileTestCodeButton")
        self.verticalLayout_2.addWidget(self.MobileTestCodeButton)
        self.MobileTurnOnSecretChinaSpyCameraButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.MobileTurnOnSecretChinaSpyCameraButton.setObjectName("MobileTurnOnSecretChinaSpyCameraButton")
        self.verticalLayout_2.addWidget(self.MobileTurnOnSecretChinaSpyCameraButton)
        self.MobileEnableRootAccessButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.MobileEnableRootAccessButton.setObjectName("MobileEnableRootAccessButton")
        self.verticalLayout_2.addWidget(self.MobileEnableRootAccessButton)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.OSInstallButton.setText(_translate("Frame", "Install"))
        self.OSUpdateButton.setText(_translate("Frame", "Update"))
        self.OSWriteCodeButton.setText(_translate("Frame", "WriteCode"))
        self.OSTestCodeButton.setText(_translate("Frame", "TestCode"))
        self.OSRebootSystemButton.setText(_translate("Frame", "RebootSystem"))
        self.OSAddUserButton.setText(_translate("Frame", "AddUser"))
        self.MobileInstallButton.setText(_translate("Frame", "Install"))
        self.MobileUpdateButton.setText(_translate("Frame", "Update"))
        self.pushButton_9.setText(_translate("Frame", "WriteCode"))
        self.MobileTestCodeButton.setText(_translate("Frame", "TestCode"))
        self.MobileTurnOnSecretChinaSpyCameraButton.setText(_translate("Frame", "TurnOnSecretChinaSpyCamera"))
        self.MobileEnableRootAccessButton.setText(_translate("Frame", "EnableRootAccess"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Frame = QtWidgets.QFrame()
    ui = Ui_Frame()
    ui.setupUi(Frame)
    Frame.show()
    sys.exit(app.exec_())
