# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './Task6.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(800, 600)
        self.resultLabel = QtWidgets.QLabel(Frame)
        self.resultLabel.setGeometry(QtCore.QRect(10, 10, 441, 581))
        self.resultLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.resultLabel.setStyleSheet("background-color:rgb(180,180,180)")
        self.resultLabel.setText("")
        self.resultLabel.setTextFormat(QtCore.Qt.AutoText)
        self.resultLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.resultLabel.setObjectName("resultLabel")
        self.generateButton = QtWidgets.QPushButton(Frame)
        self.generateButton.setGeometry(QtCore.QRect(550, 70, 151, 28))
        self.generateButton.setObjectName("generateButton")
        self.findButton = QtWidgets.QPushButton(Frame)
        self.findButton.setGeometry(QtCore.QRect(530, 120, 201, 28))
        self.findButton.setObjectName("findButton")

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.generateButton.setText(_translate("Frame", "Generate plant list"))
        self.findButton.setText(_translate("Frame", "Find Endangered Species"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Frame = QtWidgets.QFrame()
    ui = Ui_Frame()
    ui.setupUi(Frame)
    Frame.show()
    sys.exit(app.exec_())
