# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mainFrame = QtWidgets.QFrame(self.centralwidget)
        self.mainFrame.setGeometry(QtCore.QRect(0, 80, 801, 491))
        self.mainFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mainFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainFrame.setObjectName("mainFrame")
        self.task1Button = QtWidgets.QPushButton(self.centralwidget)
        self.task1Button.setGeometry(QtCore.QRect(10, 10, 131, 61))
        self.task1Button.setObjectName("task1Button")
        self.task2Button = QtWidgets.QPushButton(self.centralwidget)
        self.task2Button.setGeometry(QtCore.QRect(150, 10, 131, 61))
        self.task2Button.setObjectName("task2Button")
        self.task3Button = QtWidgets.QPushButton(self.centralwidget)
        self.task3Button.setGeometry(QtCore.QRect(290, 10, 131, 61))
        self.task3Button.setObjectName("task3Button")
        self.task4Button = QtWidgets.QPushButton(self.centralwidget)
        self.task4Button.setGeometry(QtCore.QRect(430, 10, 131, 61))
        self.task4Button.setObjectName("task4Button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.task1Button.setText(_translate("MainWindow", "Task1"))
        self.task2Button.setText(_translate("MainWindow", "Task2"))
        self.task3Button.setText(_translate("MainWindow", "Task3"))
        self.task4Button.setText(_translate("MainWindow", "Task4"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
