# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './Task2.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(800, 600)
        self.calculateButton = QtWidgets.QPushButton(Frame)
        self.calculateButton.setGeometry(QtCore.QRect(340, 300, 93, 28))
        self.calculateButton.setObjectName("calculateButton")
        self.lineEdit = QtWidgets.QLineEdit(Frame)
        self.lineEdit.setGeometry(QtCore.QRect(330, 60, 113, 22))
        self.lineEdit.setObjectName("lineEdit")
        self.coefficient = QtWidgets.QLineEdit(Frame)
        self.coefficient.setGeometry(QtCore.QRect(330, 210, 113, 22))
        self.coefficient.setObjectName("coefficient")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Frame)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(300, 130, 171, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.mark1 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.mark1.setObjectName("mark1")
        self.horizontalLayout.addWidget(self.mark1)
        self.mark2 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.mark2.setObjectName("mark2")
        self.horizontalLayout.addWidget(self.mark2)
        self.mark3 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.mark3.setObjectName("mark3")
        self.horizontalLayout.addWidget(self.mark3)
        self.mark4 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.mark4.setObjectName("mark4")
        self.horizontalLayout.addWidget(self.mark4)
        self.mark5 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.mark5.setObjectName("mark5")
        self.horizontalLayout.addWidget(self.mark5)
        self.mark6 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.mark6.setObjectName("mark6")
        self.horizontalLayout.addWidget(self.mark6)
        self.label = QtWidgets.QLabel(Frame)
        self.label.setGeometry(QtCore.QRect(360, 30, 55, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Frame)
        self.label_2.setGeometry(QtCore.QRect(340, 100, 91, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Frame)
        self.label_3.setGeometry(QtCore.QRect(320, 180, 141, 16))
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.calculateButton.setText(_translate("Frame", "Вирахувати"))
        self.label.setText(_translate("Frame", "Прізвище"))
        self.label_2.setText(_translate("Frame", "Оцінки за сесію"))
        self.label_3.setText(_translate("Frame", "Коефіцієнт стараності"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Frame = QtWidgets.QFrame()
    ui = Ui_Frame()
    ui.setupUi(Frame)
    Frame.show()
    sys.exit(app.exec_())
