# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './Task1.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(800, 600)
        self.resultLabel = QtWidgets.QLabel(Frame)
        self.resultLabel.setGeometry(QtCore.QRect(10, 10, 491, 571))
        self.resultLabel.setStyleSheet("background-color:rgb(150,150,150)")
        self.resultLabel.setText("")
        self.resultLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.resultLabel.setObjectName("resultLabel")
        self.showButton = QtWidgets.QPushButton(Frame)
        self.showButton.setGeometry(QtCore.QRect(540, 120, 131, 28))
        self.showButton.setObjectName("showButton")
        self.pushButton_2 = QtWidgets.QPushButton(Frame)
        self.pushButton_2.setGeometry(QtCore.QRect(510, 170, 191, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(Frame)
        self.label.setGeometry(QtCore.QRect(510, 250, 191, 31))
        self.label.setObjectName("label")

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.showButton.setText(_translate("Frame", "Show game results"))
        self.pushButton_2.setText(_translate("Frame", "Select teams to championship"))
        self.label.setText(_translate("Frame", "Count of passed teams"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Frame = QtWidgets.QFrame()
    ui = Ui_Frame()
    ui.setupUi(Frame)
    Frame.show()
    sys.exit(app.exec_())
